version: '3'

services:
  web:
    build: .
    restart: on-failure
    ports:
      - "5555:5555"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/datahub

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
